artifact_uri: file:///c:/Users/saifu/OneDrive/Desktop/NIDOCR/runs/mlflow/655574116996732197/f6b7fee0ad9f4f12b222e0ea14426a11/artifacts
end_time: null
entry_point_name: ''
experiment_id: '655574116996732197'
lifecycle_stage: active
run_id: f6b7fee0ad9f4f12b222e0ea14426a11
run_name: train4
run_uuid: f6b7fee0ad9f4f12b222e0ea14426a11
source_name: ''
source_type: 4
source_version: ''
start_time: 1746522187907
status: 1
tags: []
user_id: saifu
